/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IDragonswapV2PoolDeployer,
  IDragonswapV2PoolDeployerInterface,
} from "../IDragonswapV2PoolDeployer";

const _abi = [
  {
    inputs: [],
    name: "parameters",
    outputs: [
      {
        internalType: "address",
        name: "factory",
        type: "address",
      },
      {
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        internalType: "address",
        name: "token1",
        type: "address",
      },
      {
        internalType: "uint24",
        name: "fee",
        type: "uint24",
      },
      {
        internalType: "int24",
        name: "tickSpacing",
        type: "int24",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IDragonswapV2PoolDeployer__factory {
  static readonly abi = _abi;
  static createInterface(): IDragonswapV2PoolDeployerInterface {
    return new utils.Interface(_abi) as IDragonswapV2PoolDeployerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDragonswapV2PoolDeployer {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IDragonswapV2PoolDeployer;
  }
}
