/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IDragonswapV2MintCallback,
  IDragonswapV2MintCallbackInterface,
} from "../IDragonswapV2MintCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount0Owed",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1Owed",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "dragonswapV2MintCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IDragonswapV2MintCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IDragonswapV2MintCallbackInterface {
    return new utils.Interface(_abi) as IDragonswapV2MintCallbackInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDragonswapV2MintCallback {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IDragonswapV2MintCallback;
  }
}
